In [7]:
import pickle


with open('data/data_1.pkl', 'rb') as f:
    data = pickle.load(f)

In [3]:
import numpy as np

def normalize_array(arr):
    """
    Normalize an array to have values between 0 and 1.
    
    Args:
    arr (numpy.ndarray): Input array.

    Returns:
    numpy.ndarray: Normalized array.
    """
    min_val = np.min(arr)
    max_val = np.max(arr)
    normalized_arr = (arr - min_val) / (max_val - min_val)
    return normalized_arr



In [8]:
x = np.array([x for x in np.array(data[0]['descriptors0'][:-1])])
y = np.array([x for x in np.array(data[0]['descriptors1'][:-1])])

In [10]:
x[0]

array([1903.5221452 , 1886.90178975, 1871.38929617, ..., 5203.37122006,
       5202.7587448 , 5202.14646735])

In [11]:
y[0]

array([ 901.59550772,  895.95159657,  890.76941027, ..., 2757.57373659,
       2757.38748176, 2757.20127892])

In [12]:
import numpy as np

train_data = []

sc = [i for i in range(0,15)]


tmp = np.array([[x,x] for x in range(0, 15)])
all_matches = np.concatenate([
tmp,
np.zeros((15,1), dtype=np.int64),  # This is effectively adding nothing
np.zeros((15,1), dtype=np.int64)   # This is effectively adding nothing
], axis=1)
    
for i in range(0,len(data)):
    data[i]['keypoints0'] = [tuple(row) for row  in np.array(data[i]['keypoints0'])]
    data[i]['keypoints1'] = [tuple(row) for row in  np.array(data[i]['keypoints1'])]

    descs0 = np.array([normalize_array(x) for x in np.array(data[i]['descriptors0'][:-1])])
    data[i]['descriptors0'] = descs0.T.reshape(15,1500,5)
    descs1 = np.array([normalize_array(x) for x in np.array(data[i]['descriptors1'][:-1])])
    data[i]['descriptors1'] = descs1.T.reshape(15,1500,5)

    for j in range(0,1500):
        kp0 = []
        kp1 = []
        desc0 = []
        desc1 = []

        for k in range(0,15):

            kp0.append(data[i]['keypoints0'][k][j])
            kp1.append(data[i]['keypoints1'][k][j])

            desc0.append(data[i]['descriptors0'][k][j])
            desc1.append(data[i]['descriptors1'][k][j])
        
        train_data.append({'keypoints0': kp0, 'keypoints1': kp1, 'descriptors0': desc0,'descriptors1': desc1, 'scores0':sc, 'scores1': sc, 'all_matches': all_matches})

    #data[i].pop('id_')
    #data[i].pop('carthesian')
    #data[i].pop('fno')

    #tmp = np.array([[x,x] for x in range(0, len(data[i]['keypoints1']))])
    ##data[i]['all_matches'] = np.concatenate([
    #tmp,
    #np.zeros((22500,1), dtype=np.int64),  # This is effectively adding nothing
    #np.zeros((22500,1), dtype=np.int64)   # This is effectively adding nothing
    #], axis=1)
    
    #train_set[i]['scores0'] = [i for i in range(0,22500)]
    #train_set[i]['scores1'] = [i for i in range(0,22500)]

In [4]:
import numpy as np
x = np.array(data[0]['descriptors0'][:-1])

In [9]:
data[0]['descriptors0'][0][1]

array([0.13819215, 0.8585088 , 0.75924188, 0.95918367, 0.96334322])

In [10]:
data[0]['descriptors1'][0][1]

array([0.13819215, 0.8585088 , 0.23470265, 0.95918367, 0.96334322])

In [13]:
train_data[0]['descriptors0'][2]

array([0.01585133, 0.91826819, 0.82311476, 0.16717886, 0.16708035])

In [14]:
train_data[0]['descriptors1'][2]

array([0.00972561, 0.91292887, 0.22796659, 0.13031161, 0.12919327])

In [102]:
np.array(data[0])

array({'keypoints0': [(array([337.46716964,  64.70765256]), array([337.17178028,  64.93585079]), array([336.87791508,  65.15849871]), array([336.58543391,  65.37587657]), array([336.29420751,  65.58824194]), array([336.00411647,  65.7958322 ]), array([335.7150499 ,  65.99886652]), array([335.4269049 ,  66.19754784]), array([335.13958568,  66.39206443]), array([334.8530028 ,  66.58259125]), array([334.56707265,  66.7692913 ]), array([334.28171697,  66.95231657]), array([333.99686231,  67.13180917]), array([333.71243969,  67.30790215]), array([333.42838414,  67.48072016]), array([333.14463448,  67.65038032]), array([332.86113287,  67.81699268]), array([332.57782485,  67.98066093]), array([332.29465863,  68.14148274]), array([332.0115854 ,  68.29955035]), array([331.7285587 ,  68.45495086]), array([331.44553449,  68.60776672]), array([331.16247098,  68.75807598]), array([330.87932833,  68.90595266]), array([330.59606868,  69.05146697]), array([330.31265586,  69.19468556]), array([330.0290

In [92]:
import numpy as np
np.array(data[1]['keypoints0']).shape
np.array(data[1]['descriptors0'][:-1]).T.reshape(22500,5).reshape(15,1500,5)[14][1499][2]



23.181026432370743

In [91]:
np.array(data[1]['descriptors0'][:-1])[2][22499]

23.181026432370743

In [64]:
np.concatenate([(22500) * np.ones((1, 0), dtype=np.int64), np.array([])[np.newaxis, :]])

array([], shape=(2, 0), dtype=float64)

In [77]:
data[0]['descriptors0'][1]

[28.66210349654888,
 28.682378578693868,
 28.70165693148337,
 28.71999665261152,
 28.737450933104984,
 28.754068599718067,
 28.769894583828467,
 28.784970328549576,
 28.799334143631203,
 28.813021516022182,
 28.826065382623863,
 28.83849637065048,
 28.850343010127204,
 28.86163192234533,
 28.872387987476788,
 28.882634494056596,
 28.89239327267801,
 28.901684815837694,
 28.910528385642696,
 28.918942110839826,
 28.926943074390174,
 28.93454739271911,
 28.941770287541637,
 28.948626151100182,
 28.95512860554501,
 28.96129055704559,
 28.967124245225396,
 28.97264128837038,
 28.977852724849733,
 28.98276905112523,
 28.987400256689725,
 28.991755856205014,
 28.995844919140136,
 28.999676097103293,
 29.0032576491166,
 29.00659746498815,
 29.009703086962098,
 29.01258172981004,
 29.015240299474712,
 29.01768541040305,
 29.01992340167679,
 29.021960352037805,
 29.023802093900738,
 29.025454226421488,
 29.02692212772885,
 29.02821096634149,
 29.02932571186126,
 29.03027114499354,
 29.031051866

In [76]:
np.array(data[0]['descriptors0'][:-1]).T.reshape(22500,5)[0]

array([5.37789263e+02, 2.86621035e+01, 2.44224124e+01, 1.52000000e+02,
       3.86375982e+04])